"""thor-rom — Jetson ROM Image Builder.

Builds a complete OS image with JetPack 7, Isaac ROS 4.1,
FP4-quantized models, MIG partitioning, and A2A server.

This is a CONFIG GENERATOR, not an image builder — it produces
the scripts and configs needed to flash a Jetson from a clean Ubuntu install.
"""

import json
import os
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from enum import Enum


class JetsonModel(Enum):
    ORIN_NANO = "orin-nano"
    ORIN_NANO_SUPER = "orin-nano-super"
    ORIN_NX = "orin-nx"
    THOR = "thor"


class UseCase(Enum):
    MARINE = "marine"
    AERIAL = "aerial"
    INDUSTRIAL = "industrial"
    HOME = "home"
    MEDICAL = "medical"
    GENERAL = "general"


@dataclass
class ROMConfig:
    jetson_model: JetsonModel = JetsonModel.ORIN_NANO
    use_case: UseCase = UseCase.GENERAL
    hostname: str = "vessel-01"
    timezone: str = "UTC"
    ssh_keys: List[str] = field(default_factory=list)
    wifi_ssid: str = ""
    wifi_password: str = ""

    # Packages
    enable_cuda: bool = True
    enable_tensorrt: bool = True
    enable_isaac_ros: bool = False  # Heavy, Orin NX+ only
    enable_docker: bool = True
    enable_ollama: bool = True
    enable_python_env: bool = True
    enable_ros2: bool = False

    # deckboss integration
    install_deckboss: bool = True
    install_vessel_bridge: bool = True
    install_a2a_r: bool = True
    preloaded_models: List[str] = field(default_factory=lambda: [
        "deepseek-r1:1.5b",
        "phi3:mini",
    ])

    # Safety
    enable_watchdog: bool = True
    enable_thermal_throttle: bool = True
    max_gpu_power_watts: int = 15

    def to_dict(self) -> dict:
        return {
            "model": self.jetson_model.value,
            "use_case": self.use_case.value,
            "hostname": self.hostname,
            "timezone": self.timezone,
            "ssh_keys": len(self.ssh_keys),
            "cuda": self.enable_cuda,
            "tensorrt": self.enable_tensorrt,
            "isaac_ros": self.enable_isaac_ros,
            "docker": self.enable_docker,
            "ollama": self.enable_ollama,
            "deckboss": self.install_deckboss,
            "vessel_bridge": self.install_vessel_bridge,
            "a2a_r": self.install_a2a_r,
            "models": self.preloaded_models,
            "watchdog": self.enable_watchdog,
            "thermal": self.enable_thermal_throttle,
            "gpu_power_w": self.max_gpu_power_watts,
        }


def generate_setup_script(config: ROMConfig) -> str:
    """Generate the main setup script for a Jetson."""
    lines = [
        "#!/bin/bash",
        "# thor-rom setup script — generated by deckboss",
        f"# Target: {config.jetson_model.value} — {config.use_case.value}",
        "set -euo pipefail",
        "",
        f'echo "=== thor-rom setup: {config.hostname} ==="',
        f"sudo hostnamectl set-hostname {config.hostname}",
        f"sudo timedatectl set-timezone {config.timezone}",
        "",
        "# System update",
        "echo '>>> Updating system...'",
        "sudo apt-get update && sudo apt-get upgrade -y",
        "",
    ]

    # SSH keys
    if config.ssh_keys:
        lines.append("# SSH keys")
        lines.append("mkdir -p ~/.ssh")
        lines.append("chmod 700 ~/.ssh")
        for key in config.ssh_keys:
            lines.append(f"echo '{key}' >> ~/.ssh/authorized_keys")
        lines.append("chmod 600 ~/.ssh/authorized_keys")
        lines.append("")

    # WiFi
    if config.wifi_ssid:
        lines.append("# WiFi")
        lines.append("sudo nmcli dev wifi connect " + config.wifi_ssid + " password " + config.wifi_password)
        lines.append("")

    # Core packages
    lines.append("# Core packages")
    core = ["git", "python3-pip", "python3-venv", "curl", "wget", "htop", "tmux", "vim"]
    lines.append(f"sudo apt-get install -y {' '.join(core)}")
    lines.append("")

    # Docker
    if config.enable_docker:
        lines.append("# Docker")
        lines.append('curl -fsSL https://get.docker.com | sh')
        lines.append("sudo usermod -aG docker $USER")
        lines.append("")

    # Python env
    if config.enable_python_env:
        lines.append("# Python environment")
        lines.append("python3 -m venv ~/venv")
        lines.append("source ~/venv/bin/activate")
        lines.append("pip install --upgrade pip")
        lines.append("")

    # Ollama
    if config.enable_ollama:
        lines.append("# Ollama")
        lines.append("curl -fsSL https://ollama.com/install.sh | sh")
        for model in config.preloaded_models:
            lines.append(f"ollama pull {model}")
        lines.append("")

    # Deckboss
    if config.install_deckboss:
        lines.append("# Deckboss")
        lines.append("pip install deckboss")
        lines.append("deckboss onboard")
        lines.append("")

    # Vessel bridge
    if config.install_vessel_bridge:
        lines.append("# Vessel Bridge")
        lines.append("pip install vessel-bridge")
        lines.append("")

    # A2A-R
    if config.install_a2a_r:
        lines.append("# A2A-R Protocol")
        lines.append("pip install a2a-r-protocol")
        lines.append("")

    # Watchdog
    if config.enable_watchdog:
        lines.append("# Hardware watchdog")
        lines.append("sudo apt-get install -y watchdog")
        lines.append("sudo systemctl enable watchdog")
        lines.append("")

    # Thermal
    if config.enable_thermal_throttle:
        lines.append("# Thermal management")
        lines.append(f"sudo nvpmodel -m 0  # Max power: {config.max_gpu_power_watts}W")
        lines.append("")

    # Domain-specific packages
    if config.use_case == UseCase.MARINE:
        lines.append("# Marine packages")
        lines.append("sudo apt-get install -y gpsd gpsd-clients python3-gps")
        lines.append("sudo systemctl enable gpsd")
    elif config.use_case == UseCase.AERIAL:
        lines.append("# Aerial packages")
        lines.append("sudo apt-get install -y libgazebo11-dev ros-humble-gazebo-ros-pkgs")

    lines.append("")
    lines.append('echo "=== thor-rom setup complete ==="')
    lines.append("echo 'Reboot recommended: sudo reboot'")

    return "\n".join(lines)


def generate_docker_compose(config: ROMConfig) -> str:
    """Generate docker-compose.yml for vessel services."""
    services = {}

    if config.install_a2a_r:
        services["a2a-server"] = {
            "image": "python:3.11-slim",
            "volumes": ["./src:/app", "./data:/data"],
            "command": "python -m a2a_r.server",
            "ports": ["8080:8080"],
            "restart": "unless-stopped",
        }

    if config.install_vessel_bridge:
        services["vessel-bridge"] = {
            "image": "python:3.11-slim",
            "volumes": ["./src:/app"],
            "devices": ["/dev/ttyUSB0:/dev/ttyUSB0", "/dev/i2c-1:/dev/i2c-1"],
            "command": "python -m vessel_bridge.bridge",
            "restart": "unless-stopped",
        }

    if config.enable_ollama:
        services["ollama"] = {
            "image": "ollama/ollama",
            "volumes": ["ollama-data:/root/.ollama"],
            "ports": ["11434:11434"],
            "deploy": {"resources": {"reservations": {"devices": [{"capabilities": ["gpu"]}]}}},
            "restart": "unless-stopped",
        }

    compose = {"version": "3.8", "services": services}
    if "ollama" in services:
        compose["volumes"] = {"ollama-data": {}}

    return json.dumps(compose, indent=2)


def generate_character_sheet(config: ROMConfig) -> dict:
    """Generate a deckboss character.yaml for this ROM config."""
    hw = {
        "device": f"Jetson {config.jetson_model.value}",
        "ram_gb": {"orin-nano": 8, "orin-nano-super": 8, "orin-nx": 16, "thor": 32}.get(config.jetson_model.value, 8),
        "shared_memory": True,
        "detected": {"audio": True},
    }

    return {
        "version": "1.0.0",
        "hardware": hw,
        "resource_plan": {
            "model_engine": "ollama",
            "max_model_gb": 4,
            "pipeline": "serial",
        },
        "models": {
            "primary": {"engine": "ollama", "model": "phi3:mini", "priority": 1},
        },
        "io": {"primary": "terminal", "secondary": []},
        "profile": f"lucineer/{config.use_case.value}",
        "role": "vessel-operator",
        "rom_version": "thor-rom-1.0",
    }


ROM_PRESETS = {
    "fishing-vessel": ROMConfig(
        jetson_model=JetsonModel.ORIN_NANO,
        use_case=UseCase.MARINE,
        hostname="fishing-vessel",
        preloaded_models=["deepseek-r1:1.5b", "phi3:mini"],
        enable_isaac_ros=False,
        max_gpu_power_watts=15,
    ),
    "drone": ROMConfig(
        jetson_model=JetsonModel.ORIN_NANO,
        use_case=UseCase.AERIAL,
        hostname="drone-01",
        preloaded_models=["deepseek-r1:1.5b"],
        enable_ros2=True,
        max_gpu_power_watts=15,
    ),
    "home-assistant": ROMConfig(
        jetson_model=JetsonModel.ORIN_NANO,
        use_case=UseCase.HOME,
        hostname="home-bot",
        preloaded_models=["phi3:mini"],
        max_gpu_power_watts=10,
    ),
    "industrial": ROMConfig(
        jetson_model=JetsonModel.ORIN_NX,
        use_case=UseCase.INDUSTRIAL,
        hostname="factory-bot",
        preloaded_models=["deepseek-r1:1.5b", "phi3:mini"],
        enable_isaac_ros=True,
        max_gpu_power_watts=25,
    ),
}
